### ISSUE TITLE
ДЗ 8

### ISSUE THREAD

**Issue by AndyAnderyan** [aksenia-y/aksenia-y#9]
### **Завдання 5**
Ось стаття яка допоможе вам розібратись:
https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing

```css
div{
  box-sizing:content-box;
  width: 200px;
  border: 8px solid blue;
  padding: 20px;
  background: yellow;
  /* Total width: 200px + (2 * 20px) + (2 * 8px) = 256px*/
}
```

### **Завдання 8**
Ваше правило розбиває речення з 2-х слів на 2 рядки, тільки якщо у зовнішного елемента не вистачає розміру (в нашому випадку це вінко браузера)
Ось правильна відповідь:
```css
  h1 span {
      width: min-content;
      display: inline-block;
  }
```

### **Завдання 1-4, 6, 7 - зроблені на 100%**
